# Generated by Django 3.2.20 on 2023-08-03 08:12

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=django_quill.fields.QuillField(),
        ),
    ]
