# Generated by Django 3.2.20 on 2023-08-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230807_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='summary',
            field=models.TextField(max_length=240),
        ),
    ]
